language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
env:
- ENV_NAME=$(./.travis/get_branch_env_name.sh)
before_script:
- wget "https://www.uncleclapton.me/static/dwb/app.${ENV_NAME}.config.js"
- npm install -g gulp-cli
script:
- gulp --env ${ENV_NAME} --buildid ${TRAVIS_COMMIT}
addons:
  ssh_known_hosts: cheddar.fuelrats.com
notifications:
  irc:
    on_success: always
    on_failure: always
    channels:
    - ircs://sorlie.co.uk:4242/#rattech
    nick: TravisCI,
    password:
      secure: sVgdMg0pozcuOvgnHB3RlDHC+fLaQQHkojOoOhgT8lBeupKT0nH1C6gs/jvznvqGVXO+OEYJiZ1KxpMteVUvQkNKuNL/snxnR4zecpB5DuweI8w64vwlMNfMWbnrBB+dTOCvlgHOAdpqLQOgg+0yJ2q8/Do7/RVHFCPWpNCcsElE0u78bA+pdKJReXQC6+bHLAPUJdasxyCPm0WdeXL2KTsguvo0aZimDUab1EWxVrw0YgcWtrlsVAHUmPl5tzQowcwKeApPB8+w1gQgYF7J/kGd0LKtAsjQnXuIojJvnsGhQZUSTIjFgYpaKjr5k7qexmm3+V6xa665dfK79O+dPwHC3shjlXt/fUVQRyzHbAUcwM4VVC3S4r6DAqyB1D8OQVfG/wywaYBloLm0vICqLR7NpL61R3f8g//AW+cnLeS9qPPTvMgkrWDro7wftm0sFhJxPuAN2apCNQaVtz3X2l/q10T1rAwR1CVYxDnKQwQtsdv1DJ4UvDCSvvwTJjaxEmDoeaqcwJ7Zq8WTuEUIIOhGm78Ol9P5dbfzfSQB97juo/2bu4b+s0165ZKyk7x5vjjQ49ryQiwbyBJ+JN7FIeDEFt0LL5BMOzXAF1KCzs38YOIchkCzdbKmOfg0fRbipQ59urFHceusEXBMfySjzie8VmW0xwrQziYugWmt8Bg=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{result}"
    - 'Change view : %{compare_url}  Build details : %{build_url}'
before_deploy:
- openssl aes-256-cbc -K $encrypted_0b2fcf215327_key -iv $encrypted_0b2fcf215327_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete --delete-after --quiet $TRAVIS_BUILD_DIR/deploy/ fuelrats@cheddar.fuelrats.com:/var/www/dispatch.fuelrats.com/prod
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: rsync -r --delete --delete-after --quiet $TRAVIS_BUILD_DIR/deploy/ fuelrats@cheddar.fuelrats.com:/var/www/dispatch.fuelrats.com/beta
  on:
    branch: beta